// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9NVpD-9glpXTptm2c29cIhzRY07ouw8',
    appId: '1:430426791205:web:f9a94ce10f44c6d1380ecc',
    messagingSenderId: '430426791205',
    projectId: 'bookonline-3da95',
    authDomain: 'bookonline-3da95.firebaseapp.com',
    storageBucket: 'bookonline-3da95.firebasestorage.app',
    measurementId: 'G-WZQP7VRN6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwKuYSfwu5qCKCWX-6vkIn-tLkrSfdb4',
    appId: '1:430426791205:android:15c1378f38dd5de2380ecc',
    messagingSenderId: '430426791205',
    projectId: 'bookonline-3da95',
    storageBucket: 'bookonline-3da95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIhEpMQmKu5AkjDII-f_edvRb770Uhqs',
    appId: '1:430426791205:ios:e6127233e5d383fd380ecc',
    messagingSenderId: '430426791205',
    projectId: 'bookonline-3da95',
    storageBucket: 'bookonline-3da95.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvIhEpMQmKu5AkjDII-f_edvRb770Uhqs',
    appId: '1:430426791205:ios:e6127233e5d383fd380ecc',
    messagingSenderId: '430426791205',
    projectId: 'bookonline-3da95',
    storageBucket: 'bookonline-3da95.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy9NVpD-9glpXTptm2c29cIhzRY07ouw8',
    appId: '1:430426791205:web:59f32e5e600e1fb6380ecc',
    messagingSenderId: '430426791205',
    projectId: 'bookonline-3da95',
    authDomain: 'bookonline-3da95.firebaseapp.com',
    storageBucket: 'bookonline-3da95.firebasestorage.app',
    measurementId: 'G-VMQXZM1B4X',
  );
}
